name: demo_92024
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_image_slideshow: ^0.1.6
  buttons_tabbar: ^1.3.13
  syncfusion_flutter_gauges: ^27.1.48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
